### ISSUE TITLE
Publish APIs in from different accounts on one dev portal

### ISSUE THREAD

**Issue by a-tan** [awslabs/aws-api-gateway-developer-portal#232] opened 2019-03-01 01:25 UTC
Admin can publish APIs hosted in API Gateway from different accounts on to one Dev Portal. These "out of account" APIs have the same support and capabilities as a normal "in the account" API. For example, customers of the Dev Portal can get an API key, associate it with a usage plan, and monitor usage.

**Comment by Trial-In-Error** [comment] 2019-03-28 17:46
Dupe of #231. Closing.

**Closed by Trial-In-Error** 2019-03-28 17:46 UTC
Labels: enhancement, low
