### ISSUE TITLE
My Dashboard displays blank page v3.0.0

### ISSUE THREAD

**Issue by GeorgeShort** [awslabs/aws-api-gateway-developer-portal#255] opened 2019-04-04 07:25 UTC
When logged into the Dev Portal (after deployment), if I select the 'My Dashboard' tab it displays a blank page. If I then refresh the page the tabs reappear with the empty api key but then immediately returns to a blank page.

**Comment by Trial-In-Error** [comment] 2019-04-04 16:33
Hmm. Does signing out & back in again fix this? If not, can you open your browser's inspector / dev tools and paste any errors you see?

**Comment by a-tan** [comment] 2019-04-05 20:39
This is a bug, we scoped down the CORS policy set on the API Gateway API for the dev portal to be the domain of the CloudFront distribution however if you specify a custom domain we don’t (incorrectly) update the CORS policy to include your custom domain.
 
We'll fix this but in the meantime you can workaround this by setting the CORS yourself, for example using the Console:
1) Navigate to the API used by the Dev Portal, it should have the same name as your CloudFormation stack used to bring up the dev portal
2) Repeat for every OPTIONS method (should be 7)
a. Click on OPTIONS
b. Action -> Enable CORS
3) Deploy

**Comment by Trial-In-Error** [comment] 2019-04-29 19:49
Hmm, I'm not certain this is the same issue. I can't reproduce; @GeorgeShort, do you have any screenshots or more detailed steps to reproduce?

**Comment by Trial-In-Error** [comment] 2019-05-10 19:48
Closing this; believe it should be fixed in #261 / v3.0.1.

**Closed by Trial-In-Error** 2019-05-10 19:48 UTC
Labels: bug, high
