### ISSUE TITLE
API list does not toggle on the list of APIs wh

### ISSUE THREAD

**Issue by qcom-eug** [awslabs/aws-api-gateway-developer-portal#389] opened 2020-04-30 22:54 UTC
The list of APIs on the left side bar is not toggling when the code is deployed from git. I cannot pick any API on the side bar. It is just stuck. Through inspection, there seems to be no link on that div. It generates the list on that bar but cannot click.

It seems to work when it is serverless app but I need to use the one from Git. Can you please advise?

**Comment by amazon-meaisiah** [comment] 2020-05-01 20:01
Duplicate of #376

**Closed by amazon-meaisiah** 2020-05-01 20:01 UTC
